spring.application.name=salao-leila
server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/salao_leila?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
